chore(con-372):updating deprecated set-output command
iStreamPlanet/github-actions pull request #344
Opened 2022-12-01 00:50 UTC by mtktran

- Set-output command is being deprecated in favor of using github enviroment files
- PR updates actions/core library and updates scripts to use github environment files

2022-12-02 22:55 UTC, mtktran reviewed
Tested by making changes to helmfile and terraform here are the following tests: 
https://github.com/iStreamPlanet/kubernetes_management/actions/runs/3605648696/jobs/6076245551
https://github.com/iStreamPlanet/kubernetes_management/actions/runs/3605648702/jobs/6076245601

2022-12-02 23:50 UTC, glichtenISP requested changes

2022-12-02 23:50 UTC, glichtenISP commented on .github/workflows/lint-pr.yml
> +      - uses: amannn/action-semantic-pull-request@v5.0.2
This update seems to be breaking the linter?

2022-12-03 00:16 UTC, mtktran commented on .github/workflows/lint-pr.yml
> +      - uses: amannn/action-semantic-pull-request@v5.0.2
@glichtenISP This has to be updated because it is also using the old set-output command

2022-12-03 00:18 UTC, glichtenISP approved these changes
Not sure why the linter is failing, but LGTM

2022-12-03 00:30 UTC, merged