[WIP]feat: IS-3260: Staleness check workflow step
iStreamPlanet/github-actions pull request #55
Opened 2020-11-09 17:23 UTC by dlongeuay

This PR implements some of the pre-work needed for https://github.com/iStreamPlanet/kubernetes_management/issues/3672

## Notes:
- Added new helmfile-action `staleness`
- Default for staleness is 30 days

This PR corresponds with https://github.com/iStreamPlanet/kubernetes_management/pull/3868

2020-11-09 17:39 UTC, CharlieSu approved these changes

2020-11-09 17:47 UTC, marcind requested changes
I don't think adding this to `helmfile-actions` is the right thing to do. The purpose of `helmfile_actions` is to provide a wrapper around the `helmfile` sub-commands, not to be a kitchen sink of everything related to helmfile. This functionality does not seem to even call `helmfile`, which to me indicates that it does not fit in this bucket. I know it will take a bit more work, but I think this functionality should be in a separate folder, something like `helmfile-lock-stale`.

2020-11-09 17:55 UTC, marcind commented on helmfile-actions/staleness.sh
> +    if [ ${dateDeltaDays} -le ${daysStale} ]; then
I'd have to look up how bash handles integer division, but comparing the staleness in terms of seconds will be more precise, as it lets you avoid issues with integer division losing fractional days precision.

2020-11-09 18:18 UTC, marcind commented on helmfile-actions/main.sh
> +  echo 'Usage: ./main.sh $command $working_directory $days_stale'
This is another symptom that you are co-opting a generic command wrapper into something specific to this staleness scenario by reserving a positional parameter. Also, making this change will break existing other usages of this action.

2020-11-09 19:07 UTC, dlongeuay commented on helmfile-actions/main.sh
> +  echo 'Usage: ./main.sh $command $working_directory $days_stale'
good call, I moved this to a separate action

2020-11-09 19:10 UTC, dlongeuay commented on helmfile-actions/staleness.sh
> +    if [ ${dateDeltaDays} -le ${daysStale} ]; then
fixed, the check is now based on seconds. I am still returning an approximate delta in days for use in the issue that will be created. I am not too familiar with floating point division in bash and not sure if it is even worth the headache to return a decimal.

2020-11-09 23:02 UTC, marcind approved these changes

2020-11-10 16:01 UTC, CharlieSu approved these changes

2020-11-10 17:12 UTC, merged