Is 3053 reporting on eks clusters versions
iStreamPlanet/github-actions pull request #83
Opened 2021-01-05 20:34 UTC by jlapierre0istream

2021-01-05 20:57 UTC, abatilo requested changes
What is this for?

2021-01-05 21:12 UTC, jlapierre0istream commented
> What is this for?

@abatilo I added a description

2021-01-05 22:19 UTC, marcind requested changes
Can you rewrite this to not be Docker-based action. Docker-based actions rebuild the action container every time the workflow runs, which adds a non-insignificant time to how long the workflow takes. Please consider rewriting this as a [composite action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action).

2021-01-06 16:30 UTC, jlapierre0istream commented
> Can you rewrite this to not be Docker-based action. Docker-based actions rebuild the action container every time the workflow runs, which adds a non-insignificant time to how long the workflow takes. Please consider rewriting this as a [composite action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action).

@marcind I refactored this to be a composite action.

2021-01-11 15:34 UTC, CharlieSu requested changes

2021-01-11 15:34 UTC, CharlieSu commented on get-cluster-info/src/main.py
> +    write_file(f"{BASE_PATH}/CLUSTERINFO.md", md_data)
I'd prefer if the file name and path were configurable.

2021-01-11 17:14 UTC, jlapierre0istream commented on get-cluster-info/src/main.py
> +    write_file(f"{BASE_PATH}/CLUSTERINFO.md", md_data)
Fixed

2021-01-11 19:58 UTC, marcind commented on get-cluster-info/src/main.py
> +                           cwd=self.cluster_path, text=True)
This assumes that the target uses asdf. This dependency should be removed. If a particular environment uses asdf, then asdf can be invoked explicitly before this action is executed.

2021-01-11 20:01 UTC, marcind commented on get-cluster-info/src/main.py
> +        self.helm_path = (self.cluster_path).replace('clusters', 'helmfiles')
This rename captures an assumption that is very specific to a particular repository structure. We should remove this assumption, and if necessary allow the right parameters to be passed into the action.

One way to do that would be to require an action input parameter containing a glob pattern defining the set of directories containing cluster definitions.

2021-01-11 20:03 UTC, marcind commented on get-cluster-info/src/main.py
> +        tools_file = f"{self.helm_path}/.tool-versions"
This also makes the assumption that `asdf` is being used. In addition, if we want to support helm2 (which we may, we still need to make a call to see what is actually running on the server, not just look at whatever version of the client happens to be active)

2021-01-11 20:04 UTC, marcind commented on get-cluster-info/src/main.py
> +    file_list = sorted(generate_file_list(BASE_PATH, 'provider.tf'))
This assumes that a particular naming convention is followed, which may not always be the case.

Instead, the list of workspaces to inspect should be passed in via an action input variable (preferably in the form of a glob pattern)

2021-01-11 20:16 UTC, marcind requested changes
I think this implementation is too tied to the layout of a particular repository. I think we can improve on it to get something more broadly applicable.
If there's not a need to implement something more generic then this action can also be moved to the repository that that it's currently designed for.

2021-01-11 22:56 UTC, jlapierre0istream commented
@marcind I'm going to take your suggestion and move this into the repository that it will be used in since it does not need to be very generic.

2021-01-11 22:56 UTC, closed without merging